/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GemJoinLikeInterface extends ethers.utils.Interface {
  functions: {
    "dec()": FunctionFragment;
    "gem()": FunctionFragment;
    "join(address,uint256)": FunctionFragment;
    "exit(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "dec", values?: undefined): string;
  encodeFunctionData(functionFragment: "gem", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "join",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exit",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "dec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "join", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exit", data: BytesLike): Result;

  events: {};
}

export class GemJoinLike extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GemJoinLikeInterface;

  functions: {
    dec(overrides?: Overrides): Promise<ContractTransaction>;

    "dec()"(overrides?: Overrides): Promise<ContractTransaction>;

    gem(overrides?: Overrides): Promise<ContractTransaction>;

    "gem()"(overrides?: Overrides): Promise<ContractTransaction>;

    join(
      arg0: string,
      arg1: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "join(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    exit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "exit(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  dec(overrides?: Overrides): Promise<ContractTransaction>;

  "dec()"(overrides?: Overrides): Promise<ContractTransaction>;

  gem(overrides?: Overrides): Promise<ContractTransaction>;

  "gem()"(overrides?: Overrides): Promise<ContractTransaction>;

  join(
    arg0: string,
    arg1: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "join(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  exit(
    arg0: string,
    arg1: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "exit(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    dec(overrides?: CallOverrides): Promise<BigNumber>;

    "dec()"(overrides?: CallOverrides): Promise<BigNumber>;

    gem(overrides?: CallOverrides): Promise<string>;

    "gem()"(overrides?: CallOverrides): Promise<string>;

    join(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "join(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    exit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "exit(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    dec(overrides?: Overrides): Promise<BigNumber>;

    "dec()"(overrides?: Overrides): Promise<BigNumber>;

    gem(overrides?: Overrides): Promise<BigNumber>;

    "gem()"(overrides?: Overrides): Promise<BigNumber>;

    join(
      arg0: string,
      arg1: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "join(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    exit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "exit(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    dec(overrides?: Overrides): Promise<PopulatedTransaction>;

    "dec()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    gem(overrides?: Overrides): Promise<PopulatedTransaction>;

    "gem()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    join(
      arg0: string,
      arg1: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "join(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    exit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "exit(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
