/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GntJoinLikeInterface extends ethers.utils.Interface {
  functions: {
    "bags(address)": FunctionFragment;
    "make(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "bags", values: [string]): string;
  encodeFunctionData(functionFragment: "make", values: [string]): string;

  decodeFunctionResult(functionFragment: "bags", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "make", data: BytesLike): Result;

  events: {};
}

export class GntJoinLike extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GntJoinLikeInterface;

  functions: {
    bags(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "bags(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    make(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

    "make(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  bags(arg0: string, overrides?: CallOverrides): Promise<string>;

  "bags(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;

  make(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

  "make(address)"(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    bags(arg0: string, overrides?: CallOverrides): Promise<string>;

    "bags(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;

    make(arg0: string, overrides?: CallOverrides): Promise<string>;

    "make(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    bags(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "bags(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    make(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    "make(address)"(arg0: string, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bags(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bags(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    make(arg0: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "make(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
