/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { HopeLike } from "./HopeLike";

export class HopeLikeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HopeLike {
    return new Contract(address, _abi, signerOrProvider) as HopeLike;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    name: "hope",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    name: "nope",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
