/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface HopeLikeInterface extends ethers.utils.Interface {
  functions: {
    "hope(address)": FunctionFragment;
    "nope(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "hope", values: [string]): string;
  encodeFunctionData(functionFragment: "nope", values: [string]): string;

  decodeFunctionResult(functionFragment: "hope", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nope", data: BytesLike): Result;

  events: {};
}

export class HopeLike extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: HopeLikeInterface;

  functions: {
    hope(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

    "hope(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    nope(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

    "nope(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  hope(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

  "hope(address)"(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  nope(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

  "nope(address)"(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    hope(arg0: string, overrides?: CallOverrides): Promise<void>;

    "hope(address)"(arg0: string, overrides?: CallOverrides): Promise<void>;

    nope(arg0: string, overrides?: CallOverrides): Promise<void>;

    "nope(address)"(arg0: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    hope(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    "hope(address)"(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    nope(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    "nope(address)"(arg0: string, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    hope(arg0: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "hope(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    nope(arg0: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "nope(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
