/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICalleeInterface extends ethers.utils.Interface {
  functions: {
    "callFunction(address,tuple,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "callFunction",
    values: [string, { owner: string; number: BigNumberish }, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "callFunction",
    data: BytesLike
  ): Result;

  events: {};
}

export class ICallee extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICalleeInterface;

  functions: {
    callFunction(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "callFunction(address,tuple,bytes)"(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  callFunction(
    sender: string,
    accountInfo: { owner: string; number: BigNumberish },
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "callFunction(address,tuple,bytes)"(
    sender: string,
    accountInfo: { owner: string; number: BigNumberish },
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    callFunction(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "callFunction(address,tuple,bytes)"(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    callFunction(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "callFunction(address,tuple,bytes)"(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    callFunction(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "callFunction(address,tuple,bytes)"(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
