/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { JugLike } from "./JugLike";

export class JugLikeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): JugLike {
    return new Contract(address, _abi, signerOrProvider) as JugLike;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32"
      }
    ],
    name: "drip",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
