/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface JugLikeInterface extends ethers.utils.Interface {
  functions: {
    "drip(bytes32)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "drip", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "drip", data: BytesLike): Result;

  events: {};
}

export class JugLike extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: JugLikeInterface;

  functions: {
    drip(arg0: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

    "drip(bytes32)"(
      arg0: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  drip(arg0: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

  "drip(bytes32)"(
    arg0: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    drip(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "drip(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    drip(arg0: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "drip(bytes32)"(arg0: BytesLike, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    drip(arg0: BytesLike, overrides?: Overrides): Promise<PopulatedTransaction>;

    "drip(bytes32)"(
      arg0: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
