/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PotLikeInterface extends ethers.utils.Interface {
  functions: {
    "pie(address)": FunctionFragment;
    "drip()": FunctionFragment;
    "join(uint256)": FunctionFragment;
    "exit(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "pie", values: [string]): string;
  encodeFunctionData(functionFragment: "drip", values?: undefined): string;
  encodeFunctionData(functionFragment: "join", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "exit", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "pie", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "join", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exit", data: BytesLike): Result;

  events: {};
}

export class PotLike extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PotLikeInterface;

  functions: {
    pie(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "pie(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    drip(overrides?: Overrides): Promise<ContractTransaction>;

    "drip()"(overrides?: Overrides): Promise<ContractTransaction>;

    join(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "join(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    exit(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "exit(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  pie(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "pie(address)"(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  drip(overrides?: Overrides): Promise<ContractTransaction>;

  "drip()"(overrides?: Overrides): Promise<ContractTransaction>;

  join(arg0: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>;

  "join(uint256)"(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  exit(arg0: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>;

  "exit(uint256)"(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    pie(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "pie(address)"(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    drip(overrides?: CallOverrides): Promise<BigNumber>;

    "drip()"(overrides?: CallOverrides): Promise<BigNumber>;

    join(arg0: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "join(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    exit(arg0: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "exit(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    pie(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "pie(address)"(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    drip(overrides?: Overrides): Promise<BigNumber>;

    "drip()"(overrides?: Overrides): Promise<BigNumber>;

    join(arg0: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "join(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    exit(arg0: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "exit(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    pie(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "pie(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    drip(overrides?: Overrides): Promise<PopulatedTransaction>;

    "drip()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    join(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "join(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    exit(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "exit(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
