/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ProxyRegistryLikeInterface extends ethers.utils.Interface {
  functions: {
    "proxies(address)": FunctionFragment;
    "build(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "proxies", values: [string]): string;
  encodeFunctionData(functionFragment: "build", values: [string]): string;

  decodeFunctionResult(functionFragment: "proxies", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "build", data: BytesLike): Result;

  events: {};
}

export class ProxyRegistryLike extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ProxyRegistryLikeInterface;

  functions: {
    proxies(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "proxies(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    build(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

    "build(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  proxies(arg0: string, overrides?: CallOverrides): Promise<string>;

  "proxies(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;

  build(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

  "build(address)"(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    proxies(arg0: string, overrides?: CallOverrides): Promise<string>;

    "proxies(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    build(arg0: string, overrides?: CallOverrides): Promise<string>;

    "build(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    proxies(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "proxies(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    build(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    "build(address)"(arg0: string, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    proxies(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proxies(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    build(arg0: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "build(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
