/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { ProxyLike } from "./ProxyLike";

export class ProxyLikeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ProxyLike {
    return new Contract(address, _abi, signerOrProvider) as ProxyLike;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
