/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { SimpleNetworkInterface } from "./SimpleNetworkInterface";

export class SimpleNetworkInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SimpleNetworkInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SimpleNetworkInterface;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "contract IERC20",
        name: "src",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "srcAmount",
        type: "uint256"
      },
      {
        internalType: "contract IERC20",
        name: "dest",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "minConversionRate",
        type: "uint256"
      }
    ],
    name: "swapTokenToToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "contract IERC20",
        name: "token",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "minConversionRate",
        type: "uint256"
      }
    ],
    name: "swapEtherToToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: true,
    stateMutability: "payable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "contract IERC20",
        name: "token",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "srcAmount",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "minConversionRate",
        type: "uint256"
      }
    ],
    name: "swapTokenToEther",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
